name: Polls
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: push repo via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          debug: true
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "."
          target: ${{ secrets.APP_DIRECTORY }}